version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - qraphql
    environment:
      GRAPHQL_URL: http://qraphql:3001
  qraphql:
    image: yalovek/yalo-graphql
    container_name: qraphql
